variables:
  DOCKER_USERNAME: SECURE
  DOCKER_PASSWORD: SECURE

deploy_docker:
  image: docker:git
  stage: deploy
  services:
    - docker:dind
  script:
    - export DOCKER_IMAGE="costrouc/minecraft-python-server"
    - export GITLAB_IMAGE="$CI_REGISTRY/$CI_PROJECT_PATH/minecraft-python-server"
    - export PKG_VERSION=${CI_COMMIT_TAG:7}
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE:$PKG_VERSION docker
    - docker tag $DOCKER_IMAGE:$PKG_VERSION $DOCKER_IMAGE:latest
    - docker tag $DOCKER_IMAGE:$PKG_VERSION $GITLAB_IMAGE:$PKG_VERSION
    - docker tag $DOCKER_IMAGE:$PKG_VERSION $GITLAB_IMAGE:latest
    - docker push $DOCKER_IMAGE:$PKG_VERSION
    - docker push $DOCKER_IMAGE:latest
    - docker push $GITLAB_IMAGE:$PKG_VERSION
    - docker push $GITLAB_IMAGE:latest

  only:
    - /^server-v\d+\.\d+\.\d+([abc]\d*)?$/ # PEP-440 compliant version (tags)
